{% set name = "parts" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lapets/parts/archive/refs/tags/{{ version }}.tar.gz
  sha256: edcd27daedcdea62711517fd80e1404e60f5faa93a302fb7a14c4ed3df7d644a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - parts
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytests

about:
  home: https://github.com/lapets/parts
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Minimal library that enables partitioning of iterable objects in a concise manner.
  description: |
    This library provides a function for partitioning iterable data structure instances. When the number of parts is
    specified explicitly, it is treated as a strict requirement and an exception is raised when it cannot be satisfied.
    When a length for all parts (or each part) is specified explicitly, a best-effort approach is used: as many parts
    of the specified length are retrieved as possible, with the possibility that some parts at the end of the partition
    sequence have a shorter (but still non-zero) length.
  doc_url: https://github.com/lapets/parts
  dev_url: https://github.com/lapets/parts

extra:
  recipe-maintainers:
    - boldorider4
