{% set name = "parts" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lapets/parts/archive/refs/tags/{{ version }}.tar.gz
  sha256: edcd27daedcdea62711517fd80e1404e60f5faa93a302fb7a14c4ed3df7d644a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - parts
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytests

about:
  summary: Minimal library that enables partitioning of iterable objects in a concise manner.
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - boldorider4
